FROM azul/zulu-openjdk-alpine:21.0.4-jdk AS build
WORKDIR /app
COPY build.gradle .
COPY settings.gradle .
COPY gradle/ gradle/
COPY gradlew .
RUN chmod +x gradlew
RUN ./gradlew dependencies --no-daemon
COPY src/ src/
COPY .git/ .git/
RUN ./gradlew build --no-daemon


FROM azul/zulu-openjdk-alpine:21.0.4-jre
WORKDIR /app
COPY --from=build /app/build/libs/*.jar app.jar
ENTRYPOINT ["java","-jar","app.jar"]
EXPOSE 8080/tcp
EXPOSE 8081/tcp