FROM maven:3.8.3-openjdk-17 AS build
WORKDIR /app
COPY pom.xml .
RUN mvn -B dependency:resolve dependency:resolve-plugins
COPY src/ src/
COPY .git/ .git/
RUN mvn -B clean package

FROM azul/zulu-openjdk-alpine:17.0.6-jre
WORKDIR /app
COPY --from=build /app/target/*.jar app.jar
ENTRYPOINT ["java","-jar","app.jar"]
EXPOSE 8080/tcp
EXPOSE 8081/tcp