FROM maven:3.9.11-eclipse-temurin-21 AS build
WORKDIR /app
COPY pom.xml .
RUN mvn -B -Daether.dependencyCollector.impl=bf dependency:go-offline
COPY src/ src/
COPY .git/ .git/
RUN mvn -B clean package

FROM azul/zulu-openjdk-alpine:21.0.4-jre
WORKDIR /app
COPY --from=build /app/target/*.jar app.jar
ENTRYPOINT ["java","-jar","app.jar"]
EXPOSE 8080/tcp
EXPOSE 8081/tcp