FROM gradle:8.14.3-jdk21 AS build
WORKDIR /app
COPY build.gradle .
COPY settings.gradle .
RUN gradle dependencies --no-daemon
COPY src/ src/
COPY .git/ .git/
RUN gradle build --no-daemon


FROM azul/zulu-openjdk-alpine:21.0.4-jre
WORKDIR /app
COPY --from=build /app/build/libs/*.jar app.jar
ENTRYPOINT ["java","-jar","app.jar"]
EXPOSE 8080/tcp
EXPOSE 8081/tcp