FROM azul/zulu-openjdk-alpine:21.0.4-jdk AS build
WORKDIR /app
COPY pom.xml .
COPY .mvn/wrapper/ .mvn/wrapper/
COPY mvnw .
RUN chmod +x mvnw
RUN ./mvnw -B -Daether.dependencyCollector.impl=bf dependency:go-offline
COPY src/ src/
COPY .git/ .git/
RUN ./mvnw -B clean package

FROM azul/zulu-openjdk-alpine:21.0.4-jre
WORKDIR /app
COPY --from=build /app/target/*.jar /app/app.jar
ENTRYPOINT ["java","-jar","app.jar"]
EXPOSE 8080/tcp
EXPOSE 8081/tcp